accent = "#5a9db3"
cursor = "#b8b5a8"
foreground = "#d2cbbe"
background = "#1a1812"
selection_foreground = "#1a1812"
selection_background = "#5a9db3"

color0 = "#2b2617"
color1 = "#b5786a"
color2 = "#7d9a7e"
color3 = "#c4a87a"
color4 = "#3e6a7d"
color5 = "#8b7a8b"
color6 = "#5a8a94"
color7 = "#d2cbbe"
color8 = "#3b3b32"
color9 = "#c78e7a"
color10 = "#8dac8e"
color11 = "#d4be8a"
color12 = "#5a9db3"
color13 = "#9b8a9b"
color14 = "#6a9aa4"
color15 = "#e0d4bf"
