set -g fish_color_normal d2cbbe
set -g fish_color_command 3e6a7d
set -g fish_color_param 5a8a94
set -g fish_color_error b5786a
set -g fish_color_keyword 8b7a8b
set -g fish_color_quote 7d9a7e
set -g fish_color_redirection c4a87a
set -g fish_color_end 5a9db3
set -g fish_color_comment 3b3b32
set -g fish_color_selection --background=5a9db3
set -g fish_pager_color_progress 5a9db3
set -g fish_pager_color_prefix 3e6a7d
set -g fish_pager_color_completion d2cbbe
set -g fish_pager_color_description 3b3b32
