background = 1a1812
foreground = d2cbbe
background-opacity = 0.82

palette = 0=2b2617
palette = 1=b5786a
palette = 2=7d9a7e
palette = 3=c4a87a
palette = 4=3e6a7d
palette = 5=8b7a8b
palette = 6=5a8a94
palette = 7=b8c4d8
palette = 8=3b3b32
palette = 9=f0808a
palette = 10=7dca9c
palette = 11=e4c87f
palette = 12=6faef0
palette = 13=ab8fe4
palette = 14=6fd0e6
palette = 15=d4dce8
